INSERT INTO client (client_name) VALUES ('Galanthus nivalis');
INSERT INTO client (client_name) VALUES ('Narcissus pseudonarcissus');
INSERT INTO client (client_name) VALUES ('Narcissus poeticus var. recurvus');
INSERT INTO client (client_name) VALUES ('Leucojum vernum');
INSERT INTO client (client_name) VALUES ('Iris pseudacorus');
INSERT INTO client (client_name) VALUES ('Crocus tommasinianus');
INSERT INTO client (client_name) VALUES ('Colchicum autumnale');
INSERT INTO client (client_name) VALUES ('Hyacinthoides non-scripta');
INSERT INTO client (client_name) VALUES ('Erythronium dens-canis');
INSERT INTO client (client_name) VALUES ('Fritillaria meleagris');
INSERT INTO client (client_name) VALUES ('Cyclamen coum');
INSERT INTO client (client_name) VALUES ('Tulipa turkestanica');
INSERT INTO client (client_name) VALUES ('Ranunculus ficaria');